name: stagingbot
on:
  issue_comment:
    types: [created]
jobs:
  stagingbot:
    if: startsWith( ${{ github.event.comment.body }}), 'stagebot foo' )
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.issue.head.repo.full_name}}
      - run: echo ${{github.event.issue.head.repo}}
      - run: |
          export COMMIT_TO_STAGE=$(echo "${{ github.event.comment.body }})" | sed -E 's/stagebot stage (e3320f).*/\1/g')
          echo "COMMIT_TO_STAGE:"
          echo $COMMIT_TO_STAGE
          mkdir clones
          cd clones
          git clone https://github.com/${{ github.repository }} repository
          cd repository
          git remote add fork https://github.com/DilumAluthge/juliahealth.github.io
          git fetch --all --prune
          git branch --delete --force staging/pull_request/${{ github.event.issue.number }} || echo "branch does not exist"
          git checkout e33202f -b staging/pull_request/${{ github.event.issue.number }}
          git push --force origin staging/pull_request/${{ github.event.issue.number }}
