name: stagebot
on:
  issue_comment:
    types: [created]
jobs:
  stagebot:
    if: startsWith( 'stagebot stage foo', 'stagebot stage' )
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-env name=COMMENT_BODY::${{ github.event.comment.body }})"
      - run: echo "::set-env name=ISSUE_NUMBER::${{ github.event.issue.number }}"
      - run: |
          export ENV_COMMIT_TO_STAGE=$(echo "stagebot stage e3320f###" | sed -E 's/stagebot stage (e3320f).*/\1/g')
          echo "::set-env name=COMMIT_TO_STAGE::$ENV_COMMIT_TO_STAGE"
      - run: echo ${{github.event.pull_request.head.repo.full_name}}
      - run: echo ${{github.event.pull_request.head.repo}}
      - run: |
          mkdir clones
          cd clones
          git clone https://github.com/${{ github.repository }} REPOSITORY
          cd REPOSITORY
          git branch --delete --force staging/pull_request/${{ github.event.issue.number }} || echo "branch does not exist"
          git checkout e3320f -b staging/pull_request/${{ github.event.issue.number }}
          git push --force origin staging/pull_request/${{ github.event.issue.number }}
